---
title: "Lab Members"
---

## Graduate Students

**Christine McGorman**

Assessing the risk of wind erosion in agriculture using remote sensing techniques to assess soil surface conditions

## Research Assistants
- Tami M

## Past Graduate Students

**Cameron Beaupre**

Prevalence and distribution of Environmentally Smart Nitrogen (ESN) polymer capsules in agricultural landscapes

**María Alejandra Luna**

Assessing the field-scale spatial variability in colour and geochemical fingerprints as it relates to understanding the sources and sinks of sediment within a watershed

**Autumn Wiebe**

Characterization of agricultural soil GHG fluxes through both the current method and a reduced sampling method

## Past Honours Thesis

**Jonathan May**

Geochemical variability of shale beds in the MB escarpment and its implications for sediment fingerprinting

**Dia Watts**

Particle density of Sphagnum moss and its influence on hydrological properties

## Past research Assistants 
- Masoud G
- Annie T
- Autumn We
- Kim D (NSERC USRA recipient)
- Joel R
- Micheal A
- Adriana A
- Maria L
- Hannah ZB
- Samantha R
