---
title: "Opportunities"
---

## Using remote sensing techniques to assess soil surface conditions
We are seeking a highly motivated and talented candidate for a Master of Science degree
program starting in January, 2022 with Brandon University (BU) and Agriculture and Agri-Food
Canada (AAFC) on using remote sensing techniques to assess soil surface conditions. In
agricultural fields, soil surface conditions such as soil cover (canopy and crop residue cover) and soil roughness (random roughness due to the size and shape of soil clods and aggregates and
oriented roughness due to the height, spacing and direction of tillage furrows) are important
factors that can strongly affect many soil landscape processes such as soil erosion and surface
hydrology. Traditional methods for measuring soil surface conditions are labour intensive and
time consuming. A cheaper and more efficient alternative is remote sensing. Various remote
sensing techniques have been used to assess soil surface conditions. However, improvements are
still needed for: 1) assessing the accuracy, efficiency and cost of different remote sensing
methods; 2) an integrated method that can be used to estimate multiple soil surface condition
parameters under Canadian crop management and soil conditions; and 3) linking remote sensing
results to soil erosion and hydrological processes. The student will join a diverse team of
researchers from AAFC, BU, as well as University of Manitoba (UM) and take the lead on field
experiment and data analysis as part of the thesis program.

**Application Deadline:** October 15, 2021

For full application details [click here](./images/MS_RS_poster_20210913.pdf)
